var name;
//DECLARING THE NAME VARIABLE.
name = " ozzy queen";
//ASSIGNED A VALUE TO THE VARIABLE. WE ASSIGNED OZZY QUEEN VALUE TO THE NAME VARIABLE.
console.log(name);
//THE FUNCTION PRINTS VARIABLES DEFINED BEFORE IT.
console.log("<br/>");

//THE <br/> IS A LINE BREAK.

var name;
//DECLARING THE NAME VARIABLE.
name = "ozzy hum"
//ASSIGNED A VALUE TO THE VARIABLE. WE ASSIGNED OZZY HUM VALUE TO THE NAME VARIABLE.
console.log(name)
//THE FUNCTION PRINTS VARIABLES DEFINED BEFORE IT.
var name;
//DECLARING THE NAME VARIABLE.
name = "sumi mike ozyy"
//ASSIGNED A VALUE TO THE VARIABLE. WE ASSIGNED SUMI MIKE OZZY VALUE TO THE NAME VARIABLE.
console.log(name)
//THE FUNCTION PRINTS VARIABLES DEFINED BEFORE IT.
var name;
//DECLARING THE NAME VARIABLE.
name = " ozzy bp"
//ASSIGNED A VALUE TO THE VARIABLE. WE ASSIGNED OZZY BP TO THE NAME VARIABLE.
console.log(name)
//THE FUNCTION PRINTS VARIABLES DEFINED BEFORE IT.
name = " Bridget ozzy"
/*VAR DECLARES A VARIABLE AND SINCE WE HAVE ALREADY DECLARED THE NAME VARIABLE IN THE PREVIOUS EXAMPLES
ITS OK IF ITS NOT DECLARED AGAIN.*/
//ASSIGNED A VALUE TO THE VARIABLE. WE ASSIGNED BRIDGET OZZY TO THE NAME VARIABLE.
console.log(name)
//THE FUNCTION PRINTS VARIABLES DEFINED BEFORE IT.



var age;
//DECLARING THE AGE VARIABLE.
var name;
//DECLARING THE NAME VARIABLE. 
age = 50;
name = "mirembe agaba kwesi"
//ASSIGNING VALUES 50 AND MIREMBE AGABA KWESI TO AGE AND NAME VARIABLES RESPECTIVELY.
document.write("My name is " +name +" "+ "and I am "+age+" "+" years old");
/*THE METHOD IS SUPPOSED TO WRITE JAVASCRIPT CODE TO A DOCUMENT.
THE (+) OPERATOR HELPS US TO COMBINE THE STRINGS.*/
var x;
//THE VARIABLE WAS DECLARED BUT NOT ASSIGNED ANY VALUE
document.write(x);
//THE METHOD IS SUPPOSED TO WRITE JAVASCRIPT CODE TO A DOCUMENT.
var x = undefined;
//UNDEFINED IS ASSIGNED TO VARIABLE X BECAUSE IT WAS NOT DEFINED WITH A VALUE.
console.log(x);
//THE FUNCTION PRINTS VARIABLES DEFINED BEFORE IT.